languageCode = "pt-br"
languageName = "Português Brasil"
weight = 2
title = "JE"

[params]
displayName = "Português Brasil"
isoCode = "pt-BR"
rtl = false
dateFormat = "02 de January de 2006"
logo = "img/logo_inverted@0.25x.png"
secondaryLogo = "img/logo@0.25x.png"
description = "JE | John Enderson"
#copyright = "Copy, _right?_ :thinking_face:"